name: Sent message to Discord

on: [ push ]
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Sent message to Discord
      uses: appleboy/discord-action@0.0.3
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#48f442"
        username: "GitHub bot test"
        args: The ${{ github.event_name }} event triggered. ${{ needs.job1.outputs.output1 }} ${{needs.job1.outputs.output2}}!
